### PR TITLE
I have made the changes here, and I have ensured that the code runs on all examples. 

### PR DESCRIPTION
**Pull request by aviralkumar2907**
Please make sure you do the following before issuing a pull request:
- [ ] All unit and regression tests pass (run `ant test`)
- [ ] Any new features have some tests in the standard test suite (junit) which confirms they are working as expected
- [ ] All new code is clean and doesn't contain debug printing or dead code

### CODE REVIEW

**Comment by aviralkumar2907** [comment]
Also, I have updates the PyRRTPrinter,java with TRUE/FALSE.
There needs to be one more change,. When the inv and der lambda dunctions are printed, please remove the underscore here : `lambda _, state :`. I couldn't find the code for this in the Pyrrtprinter, and it seems that this is imported from some other file. We can just copy that function in the Pyrrtprinter and then this should work.

**Comment by stanleybak** [comment]
Can you update the tool in src/hybridpy/hybridpy/pyrrt as well?

**Comment by aviralkumar2907** [comment]
What exactly is meant by the above question? Should I update something in the code which I wrote? Also, I tried finding the place where  `lambda _, state :` is mentioned but it seems that it is common with pysim. The code works on all examples and without this, I might not be able to run the tests.

**Comment by stanleybak** [comment]
The first instruction for the pull request is "All unit and regression tests pass (run ant test)". When I go to `hyst/src` and type `ant test`, the tests fail. Here's a log message:

```
Test failed for 2/90 model lorenz with pyrrt: Error (Tool)

Log:
Running pyrrt on model /home/stan/Desktop/temp/hyst_temp/hyst/src/tests/regression/models/lorenz/lorenz.xml
Hyst command: ['java', '-jar', '/home/stan/Desktop/temp/hyst_temp/hyst/src/tests/regression/../../Hyst.jar', '/home/stan/Desktop/temp/hyst_temp/hyst/src/tests/regression/models/lorenz/lorenz.xml', '-o', '/home/stan/Desktop/temp/hyst_temp/hyst/src/tests/regression/result/lorenz_pyrrt.py', '-pyrrt']

Finished converting in 474 ms
Seconds for Hyst conversion: 2.05833792686
Traceback (most recent call last):
  File "/home/stan/Desktop/temp/hyst_temp/hyst/src/hybridpy/hybridpy/tool_pyrrt.py", line 54, in <module>
    tool_main(PyRrtTool())
  File "/home/stan/Desktop/temp/hyst_temp/hyst/src/hybridpy/hybridpy/hybrid_tool.py", line 75, in tool_main
    code = tool_obj.run()
  File "/home/stan/Desktop/temp/hyst_temp/hyst/src/hybridpy/hybridpy/hybrid_tool.py", line 271, in run
    rv = self._run_tool()
  File "/home/stan/Desktop/temp/hyst_temp/hyst/src/hybridpy/hybridpy/tool_pyrrt.py", line 30, in _run_tool
    self._result = run()
  File "/tmp/pyrrt_550_903946/lorenz_pyrrt.py", line 40, in run
  File "/home/stan/Desktop/temp/hyst_temp/hyst/src/hybridpy/hybridpy/pyrrt/expt_opt.py", line 1133, in run
    my_rrt = RRT(ha, list_of_initial_states, init_states[0][0])
  File "/home/stan/Desktop/temp/hyst_temp/hyst/src/hybridpy/hybridpy/pyrrt/expt_opt.py", line 342, in __init__
    self.ha.modes[modes].inv_strings, self.ha.variables)
  File "/home/stan/Desktop/temp/hyst_temp/hyst/src/hybridpy/hybridpy/pyrrt/util.py", line 45, in parser
    b.append(float(eq_1[1]))
IndexError: list index out of range
Elapsed Seconds: 2.52643799782
Result: Error (Tool)
```

It looks like the error is in `hyst/src/hybridpy/hybridpy/pyrrt/util.py`. Is this the latest code for the tool? Please ensure the tests run. Do they run on your machine? Perhaps you have `$PYTHONPATH` set to use a different version of the tool. Unset this before running the tests to ensure it uses the one in the repository.

**Pull request closed without merging**
